Update Pi.Alert to version 0.0.6
## 0.0.6
### ✨ Features
- Updated to v2024-09-28 (https://github.com/leiweibau/Pi.Alert/releases/tag/v2024-09-28)

### 🩹 BugFix
- Fix missing MQTT notifications visibility on 'Settings and Maintenance' page.
- Enabled DB update in install-pialert.sh

diff --git a/pialert/rootfs/root/pialert/back/pialert-cli b/pialert/rootfs/root/pialert/back/pialert-cli
--- a/pialert/rootfs/root/pialert/back/pialert-cli
+++ b/pialert/rootfs/root/pialert/back/pialert-cli
@@ -1,5 +1,5 @@
 #!/bin/bash
-SCRIPTVERSION='v1.25'
+SCRIPTVERSION='v1.27'
 SCRIPT=$(readlink -f $0)
 SCRIPTPATH=`dirname $SCRIPT`
 PIA_CONF_FILE=${SCRIPTPATH}'/../config/pialert.conf'
@@ -219,6 +219,9 @@ EOM
     echo "Configured Pi.Alert scans are disabled"
     if [ "$CURRENT_USER" != "www-data" ]; then
         sqlite3 $PIA_DB_FILE "INSERT INTO 'pialert_journal' ('Journal_DateTime', 'LogClass', 'Trigger', 'LogString', 'Hash', 'Additional_Info') VALUES('$(date '+%Y-%m-%d %H:%M:%S')', 'b_002', 'pialert-cli', 'LogStr_0511', '', '${STOPTIMER} min');"
+        if [ $? -ne 0 ]; then
+            echo "Failed to write to the journal, but continuing."
+        fi
     fi
 
     ;;
@@ -606,6 +609,22 @@ EOM
       sqlite3 $PIA_DB_FILE "ALTER TABLE 'Satellites' ADD COLUMN 'sat_conf_scan_unifi' BOOLEAN NOT NULL DEFAULT 0;"
     else
       echo "        Column 'sat_conf_scan_unifi' already exists in the 'Satellites' table."
+    fi
+    # Satellites.sat_host_data
+    echo -e "...Insert new column 'sat_host_data' to table 'Satellites' to DB"    
+    existing=$(sqlite3 $PIA_DB_FILE "PRAGMA table_info('Satellites');" | awk -F\| '{print $2}' | grep -wci "sat_host_data")
+    if [ $existing -eq 0 ]; then
+      sqlite3 $PIA_DB_FILE "ALTER TABLE 'Satellites' ADD COLUMN 'sat_host_data' TEXT;"
+    else
+      echo "        Column 'sat_host_data' already exists in the 'Satellites' table."
+    fi
+    # Devices.dev_PresencePage
+    echo -e "...Insert new column 'dev_PresencePage' to table 'Devices' to DB"    
+    existing=$(sqlite3 $PIA_DB_FILE "PRAGMA table_info('Devices');" | awk -F\| '{print $2}' | grep -wci "dev_PresencePage")
+    if [ $existing -eq 0 ]; then
+      sqlite3 $PIA_DB_FILE "ALTER TABLE 'Devices' ADD COLUMN 'dev_PresencePage' BOOLEAN NOT NULL DEFAULT 1;"
+    else
+      echo "        Column 'dev_PresencePage' already exists in the 'Devices' table."
     fi
 
     echo -e "\nUpdate finished!\n"
